#!/usr/bin/env python3
"""
Rabbit Simulation Visualization Script

This script reads CSV log files generated by the rabbit simulation and creates
comprehensive visualizations including:
- Population growth over time (comparing multiple simulations)
- Sex distribution dynamics
- Birth/death rates
- Age distribution changes
- Statistical summary from all simulations
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import glob
import os
from pathlib import Path

# Configuration
FIGURE_SIZE = (14, 10)
DPI = 100
COLORS = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D', '#6A994E']

def load_simulation_data(pattern="simulation_*.csv"):
    """Load all individual simulation CSV files."""
    files = sorted(glob.glob(pattern))
    
    # Filter out summary files
    files = [f for f in files if 'summary' not in f.lower()]
    
    simulations = []
    for file in files:
        try:
            df = pd.read_csv(file)
            # Extract simulation number from filename pattern: simulation_N_popM.csv
            # Split by '_' and get the second element (index 1)
            parts = file.replace('.csv', '').split('_')
            sim_number = int(parts[1])  # This gets N from simulation_N_popM.csv
            simulations.append((sim_number, df, file))
            print(f"  Loaded {file} as Simulation {sim_number}")
        except Exception as e:
            print(f"Warning: Could not load {file}: {e}")
    
    # Sort by simulation number to ensure correct order
    simulations.sort(key=lambda x: x[0])
    
    return simulations

def load_summary_data(pattern="simulation_summary_*.csv"):
    """Load the summary file containing all simulation results."""
    files = glob.glob(pattern)
    if not files:
        return None
    
    try:
        # Read the file, skipping comment lines
        df = pd.read_csv(files[0], comment='#')
        return df
    except Exception as e:
        print(f"Warning: Could not load summary file: {e}")
        return None

def plot_population_growth_comparison(simulations, max_sims=3):
    """Plot population growth over time for multiple simulations."""
    fig, ax = plt.subplots(figsize=FIGURE_SIZE, dpi=DPI)
    
    for i, (sim_num, df, filename) in enumerate(simulations[:max_sims]):
        color = COLORS[i % len(COLORS)]
        ax.plot(df['Month'], df['Total_Alive'], 
                label=f'Simulation {sim_num}', 
                linewidth=2, color=color, alpha=0.8)
    
    ax.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax.set_ylabel('Population', fontsize=12, fontweight='bold')
    ax.set_title('Rabbit Population Growth Over Time', fontsize=14, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('population_growth_comparison.png', dpi=DPI, bbox_inches='tight')
    print("✓ Saved: population_growth_comparison.png")
    plt.close()

def plot_sex_distribution(simulations, max_sims=3):
    """Plot sex distribution over time for multiple simulations using stacked area charts."""
    fig, axes = plt.subplots(max_sims, 1, figsize=(12, 4*max_sims), dpi=DPI)
    
    if max_sims == 1:
        axes = [axes]
    
    for idx, (sim_num, df, filename) in enumerate(simulations[:max_sims]):
        ax = axes[idx]
        
        # Use stacked area chart for better visibility
        ax.fill_between(df['Month'], 0, df['Males'], 
                        label='Males', color='#2E86AB', alpha=0.6)
        ax.fill_between(df['Month'], df['Males'], df['Males'] + df['Females'], 
                        label='Females', color='#A23B72', alpha=0.6)
        
        # Add total population line for reference
        ax.plot(df['Month'], df['Total_Alive'], 
                label='Total', color='black', linewidth=2, linestyle='--', alpha=0.7)
        
        ax.set_xlabel('Month', fontsize=11, fontweight='bold')
        ax.set_ylabel('Count', fontsize=11, fontweight='bold')
        ax.set_title(f'Simulation {sim_num}: Sex Distribution Over Time (Stacked)', 
                    fontsize=12, fontweight='bold')
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('sex_distribution.png', dpi=DPI, bbox_inches='tight')
    print("✓ Saved: sex_distribution.png")
    plt.close()

def plot_birth_death_rates(simulations, sim_index=0):
    """Plot birth and death rates over time for a single simulation."""
    if not simulations:
        return
    
    sim_num, df, filename = simulations[sim_index]
    
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 10), dpi=DPI)
    
    # Births and Deaths
    ax1.plot(df['Month'], df['Births'], label='Births', 
            color='#6A994E', linewidth=2, alpha=0.8)
    ax1.plot(df['Month'], df['Deaths'], label='Deaths', 
            color='#C73E1D', linewidth=2, alpha=0.8)
    ax1.set_xlabel('Month', fontsize=11, fontweight='bold')
    ax1.set_ylabel('Count', fontsize=11, fontweight='bold')
    ax1.set_title(f'Simulation {sim_num}: Births and Deaths per Month', 
                 fontsize=12, fontweight='bold')
    ax1.legend(fontsize=10)
    ax1.grid(True, alpha=0.3)
    
    # Net Growth (Births - Deaths)
    net_growth = df['Births'] - df['Deaths']
    ax2.plot(df['Month'], net_growth, label='Net Growth', 
            color='#F18F01', linewidth=2, alpha=0.8)
    ax2.axhline(y=0, color='black', linestyle='--', linewidth=1, alpha=0.5)
    ax2.set_xlabel('Month', fontsize=11, fontweight='bold')
    ax2.set_ylabel('Net Growth', fontsize=11, fontweight='bold')
    ax2.set_title(f'Simulation {sim_num}: Net Population Growth per Month', 
                 fontsize=12, fontweight='bold')
    ax2.legend(fontsize=10)
    ax2.grid(True, alpha=0.3)
    
    # Average Age
    ax3.plot(df['Month'], df['Avg_Age'], label='Average Age', 
            color='#2E86AB', linewidth=2, alpha=0.8)
    ax3.set_xlabel('Month', fontsize=11, fontweight='bold')
    ax3.set_ylabel('Age (months)', fontsize=11, fontweight='bold')
    ax3.set_title(f'Simulation {sim_num}: Average Population Age', 
                 fontsize=12, fontweight='bold')
    ax3.legend(fontsize=10)
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(f'birth_death_analysis_sim{sim_num}.png', dpi=DPI, bbox_inches='tight')
    print(f"✓ Saved: birth_death_analysis_sim{sim_num}.png")
    plt.close()

def plot_maturity_pregnancy(simulations, sim_index=0):
    """Plot maturity and pregnancy statistics for a single simulation."""
    if not simulations:
        return
    
    sim_num, df, filename = simulations[sim_index]
    
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), dpi=DPI)
    
    # Mature rabbits vs Total
    ax1.plot(df['Month'], df['Total_Alive'], label='Total Population', 
            color='#2E86AB', linewidth=2, alpha=0.8)
    ax1.plot(df['Month'], df['Mature_Rabbits'], label='Mature Rabbits', 
            color='#F18F01', linewidth=2, alpha=0.8)
    ax1.set_xlabel('Month', fontsize=11, fontweight='bold')
    ax1.set_ylabel('Count', fontsize=11, fontweight='bold')
    ax1.set_title(f'Simulation {sim_num}: Mature Rabbits vs Total Population', 
                 fontsize=12, fontweight='bold')
    ax1.legend(fontsize=10)
    ax1.grid(True, alpha=0.3)
    
    # Pregnant females
    ax2.plot(df['Month'], df['Pregnant_Females'], label='Pregnant Females', 
            color='#A23B72', linewidth=2, alpha=0.8)
    ax2.set_xlabel('Month', fontsize=11, fontweight='bold')
    ax2.set_ylabel('Count', fontsize=11, fontweight='bold')
    ax2.set_title(f'Simulation {sim_num}: Pregnant Females Over Time', 
                 fontsize=12, fontweight='bold')
    ax2.legend(fontsize=10)
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(f'maturity_pregnancy_sim{sim_num}.png', dpi=DPI, bbox_inches='tight')
    print(f"✓ Saved: maturity_pregnancy_sim{sim_num}.png")
    plt.close()

def plot_sex_percentage_over_time(simulations, max_sims=3):
    """Plot sex percentage distribution over time."""
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), dpi=DPI)
    
    # Top plot: Male percentage over time
    for i, (sim_num, df, filename) in enumerate(simulations[:max_sims]):
        color = COLORS[i % len(COLORS)]
        ax1.plot(df['Month'], df['Male_Percentage'], 
                label=f'Simulation {sim_num}', 
                linewidth=2, color=color, alpha=0.8)
    
    ax1.axhline(y=50, color='black', linestyle='--', linewidth=1, alpha=0.5, 
               label='50% (Expected)')
    ax1.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Male Percentage (%)', fontsize=12, fontweight='bold')
    ax1.set_title('Male Percentage Over Time', fontsize=14, fontweight='bold')
    ax1.set_ylim([0, 100])
    ax1.legend(fontsize=10)
    ax1.grid(True, alpha=0.3)
    
    # Bottom plot: Sex ratio (Males per 100 Females)
    for i, (sim_num, df, filename) in enumerate(simulations[:max_sims]):
        color = COLORS[i % len(COLORS)]
        # Calculate sex ratio (avoid division by zero)
        sex_ratio = df.apply(lambda row: (row['Males'] / row['Females'] * 100) 
                            if row['Females'] > 0 else 0, axis=1)
        ax2.plot(df['Month'], sex_ratio, 
                label=f'Simulation {sim_num}', 
                linewidth=2, color=color, alpha=0.8)
    
    ax2.axhline(y=100, color='black', linestyle='--', linewidth=1, alpha=0.5, 
               label='100 (Equal ratio)')
    ax2.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Males per 100 Females', fontsize=12, fontweight='bold')
    ax2.set_title('Sex Ratio Over Time', fontsize=14, fontweight='bold')
    ax2.legend(fontsize=10)
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('sex_percentage_over_time.png', dpi=DPI, bbox_inches='tight')
    print("✓ Saved: sex_percentage_over_time.png")
    plt.close()


def generate_statistics_report(simulations, summary_df):
    """Generate a text report with key statistics."""
    with open('simulation_report.txt', 'w') as f:
        f.write("="*70 + "\n")
        f.write(" RABBIT SIMULATION ANALYSIS REPORT\n")
        f.write("="*70 + "\n\n")
        
        if simulations:
            f.write(f"Individual Simulations Logged: {len(simulations)}\n")
            for sim_num, df, filename in simulations:
                f.write(f"\n--- Simulation {sim_num} ({filename}) ---\n")
                f.write(f"  Duration: {len(df)} months\n")
                f.write(f"  Final Population: {df['Total_Alive'].iloc[-1]}\n")
                f.write(f"  Peak Population: {df['Total_Alive'].max()} (Month {df['Total_Alive'].idxmax()})\n")
                f.write(f"  Final Male %: {df['Male_Percentage'].iloc[-1]:.2f}%\n")
                f.write(f"  Total Births: {df['Births'].sum()}\n")
                f.write(f"  Total Deaths: {df['Deaths'].sum()}\n")
                f.write(f"  Average Age at End: {df['Avg_Age'].iloc[-1]:.2f} months\n")
        
        if summary_df is not None:
            f.write(f"\n\n{'='*70}\n")
            f.write("SUMMARY ACROSS ALL SIMULATIONS\n")
            f.write(f"{'='*70}\n")
            f.write(f"Total Simulations: {len(summary_df)}\n\n")
            
            f.write("Final Population Statistics:\n")
            f.write(f"  Mean: {summary_df['Final_Alive'].mean():.2f}\n")
            f.write(f"  Median: {summary_df['Final_Alive'].median():.2f}\n")
            f.write(f"  Std Dev: {summary_df['Final_Alive'].std():.2f}\n")
            f.write(f"  Min: {summary_df['Final_Alive'].min()}\n")
            f.write(f"  Max: {summary_df['Final_Alive'].max()}\n\n")
            
            f.write("Peak Population Statistics:\n")
            f.write(f"  Mean: {summary_df['Peak_Pop'].mean():.2f}\n")
            f.write(f"  Median: {summary_df['Peak_Pop'].median():.2f}\n")
            f.write(f"  Std Dev: {summary_df['Peak_Pop'].std():.2f}\n")
            f.write(f"  Min: {summary_df['Peak_Pop'].min()}\n")
            f.write(f"  Max: {summary_df['Peak_Pop'].max()}\n\n")
            
            extinct_count = (summary_df['Extinction_Month'] > 0).sum()
            f.write(f"Extinction Analysis:\n")
            f.write(f"  Extinctions: {extinct_count} ({extinct_count/len(summary_df)*100:.2f}%)\n")
            f.write(f"  Survived: {len(summary_df) - extinct_count}\n")
            if extinct_count > 0:
                extinct_df = summary_df[summary_df['Extinction_Month'] > 0]
                f.write(f"  Average Extinction Month: {extinct_df['Extinction_Month'].mean():.2f}\n")
            
            f.write(f"\nSex Distribution:\n")
            f.write(f"  Mean Male %: {summary_df['Male_Pct'].mean():.2f}%\n")
            f.write(f"  Std Dev: {summary_df['Male_Pct'].std():.2f}%\n")
    
    print("✓ Saved: simulation_report.txt")

def main():
    """Main function to generate all visualizations."""
    print("\n" + "="*70)
    print(" RABBIT SIMULATION VISUALIZATION")
    print("="*70 + "\n")
    
    # Load data
    print("Loading simulation data...")
    simulations = load_simulation_data()
    summary_df = load_summary_data()
    
    if not simulations and summary_df is None:
        print("❌ Error: No simulation data files found!")
        print("   Make sure CSV files are in the current directory.")
        return
    
    print(f"✓ Found {len(simulations)} individual simulation log(s)")
    if summary_df is not None:
        print(f"✓ Found summary data with {len(summary_df)} simulation(s)")
    
    print("\nGenerating visualizations...\n")
    
    # Generate plots
    if simulations:
        plot_population_growth_comparison(simulations)
        plot_sex_distribution(simulations)
        plot_sex_percentage_over_time(simulations)
        plot_birth_death_rates(simulations, 0)
        plot_maturity_pregnancy(simulations, 0)
    
    #if summary_df is not None:
    #    plot_summary_statistics(summary_df)

    # Generate text report
    generate_statistics_report(simulations, summary_df)
    
    print("\n" + "="*70)
    print(" ✓ All visualizations generated successfully!")
    print("="*70 + "\n")

if __name__ == "__main__":
    main()