#!/usr/bin/env python3
"""
Rabbit Simulation Data Visualization Script

This script reads CSV files generated by the rabbit simulation C program
and creates comprehensive visualizations of population dynamics.

Required files:
- monthly_averages.csv: Aggregated monthly data across all simulations
- summary_stats.csv: Overall summary statistics
- simulation_*.csv: Individual simulation data (optional)

Usage:
    python visualize_rabbits.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path
import sys

# Set style for better-looking plots
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (14, 10)
plt.rcParams['font.size'] = 10


def load_data():
    """
    Load all CSV data files from the simulation.
    
    Returns:
        tuple: (monthly_avg_df, summary_df, individual_sims_list) or None if files not found
    """
    try:
        # Load aggregated monthly averages
        monthly_avg = pd.read_csv('monthly_averages.csv')
        
        # Load summary statistics
        summary = pd.read_csv('summary_stats.csv')
        
        # Load individual simulations (if they exist)
        individual_sims = []
        for sim_file in sorted(Path('.').glob('simulation_*.csv')):
            try:
                df = pd.read_csv(sim_file)
                individual_sims.append(df)
            except Exception as e:
                print(f"Warning: Could not load {sim_file}: {e}")
        
        return monthly_avg, summary, individual_sims
    
    except FileNotFoundError as e:
        print(f"Error: Required data file not found: {e}")
        print("Please run the C simulation first to generate CSV files.")
        return None


def plot_population_growth(monthly_data, summary_data):
    """
    Create a comprehensive plot showing population growth over time with confidence intervals.
    
    Args:
        monthly_data (DataFrame): Monthly averages data
        summary_data (DataFrame): Summary statistics
    """
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Rabbit Population Dynamics Analysis', fontsize=16, fontweight='bold')
    
    # Extract initial population from summary
    initial_pop = int(summary_data[summary_data['metric'] == 'initial_population']['value'].values[0])
    
    # 1. Population Growth with Confidence Interval
    ax1 = axes[0, 0]
    ax1.plot(monthly_data['month'], monthly_data['avg_alive'], 
             linewidth=2, color='#2E86AB', label='Average Population')
    
    # Add confidence interval (mean ± std)
    ax1.fill_between(monthly_data['month'], 
                     monthly_data['avg_alive'] - monthly_data['std_alive'],
                     monthly_data['avg_alive'] + monthly_data['std_alive'],
                     alpha=0.3, color='#2E86AB', label='±1 Std Dev')
    
    ax1.set_xlabel('Month', fontweight='bold')
    ax1.set_ylabel('Population', fontweight='bold')
    ax1.set_title('Population Growth Over Time', fontweight='bold')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # 2. Births vs Deaths
    ax2 = axes[0, 1]
    ax2.plot(monthly_data['month'], monthly_data['avg_births'], 
             linewidth=2, color='#06A77D', label='Births', marker='o', markersize=3)
    ax2.plot(monthly_data['month'], monthly_data['avg_deaths'], 
             linewidth=2, color='#D62246', label='Deaths', marker='s', markersize=3)
    
    ax2.set_xlabel('Month', fontweight='bold')
    ax2.set_ylabel('Count', fontweight='bold')
    ax2.set_title('Births vs Deaths per Month', fontweight='bold')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # 3. Sex Distribution Over Time
    ax3 = axes[1, 0]
    ax3.plot(monthly_data['month'], monthly_data['avg_males'], 
             linewidth=2, color='#4A90E2', label='Males', alpha=0.8)
    ax3.plot(monthly_data['month'], monthly_data['avg_females'], 
             linewidth=2, color='#E24A90', label='Females', alpha=0.8)
    
    ax3.set_xlabel('Month', fontweight='bold')
    ax3.set_ylabel('Population', fontweight='bold')
    ax3.set_title('Sex Distribution Over Time', fontweight='bold')
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # 4. Reproductive Status
    ax4 = axes[1, 1]
    ax4.plot(monthly_data['month'], monthly_data['avg_mature'], 
             linewidth=2, color='#F18F01', label='Mature Rabbits')
    ax4.plot(monthly_data['month'], monthly_data['avg_pregnant'], 
             linewidth=2, color='#C73E1D', label='Pregnant Females')
    
    ax4.set_xlabel('Month', fontweight='bold')
    ax4.set_ylabel('Count', fontweight='bold')
    ax4.set_title('Reproductive Status Over Time', fontweight='bold')
    ax4.legend()
    ax4.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('population_dynamics.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: population_dynamics.png")


def plot_growth_rate(monthly_data):
    """
    Calculate and plot population growth rate over time.
    
    Args:
        monthly_data (DataFrame): Monthly averages data
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle('Population Growth Rate Analysis', fontsize=16, fontweight='bold')
    
    # Calculate growth rate (net change per month)
    monthly_data['net_growth'] = monthly_data['avg_births'] - monthly_data['avg_deaths']
    monthly_data['growth_rate'] = (monthly_data['avg_alive'].diff() / 
                                    monthly_data['avg_alive'].shift(1) * 100)
    
    # 1. Net Growth (Births - Deaths)
    ax1 = axes[0]
    colors = ['#06A77D' if x >= 0 else '#D62246' for x in monthly_data['net_growth']]
    ax1.bar(monthly_data['month'], monthly_data['net_growth'], 
            color=colors, alpha=0.7, edgecolor='black', linewidth=0.5)
    ax1.axhline(y=0, color='black', linestyle='-', linewidth=1)
    ax1.set_xlabel('Month', fontweight='bold')
    ax1.set_ylabel('Net Growth (Births - Deaths)', fontweight='bold')
    ax1.set_title('Net Population Change per Month', fontweight='bold')
    ax1.grid(True, alpha=0.3, axis='y')
    
    # 2. Growth Rate Percentage
    ax2 = axes[1]
    ax2.plot(monthly_data['month'][1:], monthly_data['growth_rate'][1:], 
             linewidth=2, color='#2E86AB', marker='o', markersize=4)
    ax2.axhline(y=0, color='red', linestyle='--', linewidth=1, alpha=0.7)
    ax2.set_xlabel('Month', fontweight='bold')
    ax2.set_ylabel('Growth Rate (%)', fontweight='bold')
    ax2.set_title('Month-over-Month Growth Rate', fontweight='bold')
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('growth_rate_analysis.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: growth_rate_analysis.png")


def plot_sex_ratio(monthly_data):
    """
    Analyze and plot sex ratio dynamics.
    
    Args:
        monthly_data (DataFrame): Monthly averages data
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle('Sex Ratio Analysis', fontsize=16, fontweight='bold')
    
    # Calculate sex ratio (males per 100 females)
    monthly_data['sex_ratio'] = (monthly_data['avg_males'] / 
                                  monthly_data['avg_females'] * 100)
    monthly_data['male_percentage'] = (monthly_data['avg_males'] / 
                                        monthly_data['avg_alive'] * 100)
    
    # 1. Sex Ratio Over Time
    ax1 = axes[0]
    ax1.plot(monthly_data['month'], monthly_data['sex_ratio'], 
             linewidth=2.5, color='#6A4C93', marker='o', markersize=4)
    ax1.axhline(y=100, color='red', linestyle='--', linewidth=2, 
                label='Equal Ratio (100)', alpha=0.7)
    ax1.set_xlabel('Month', fontweight='bold')
    ax1.set_ylabel('Males per 100 Females', fontweight='bold')
    ax1.set_title('Sex Ratio Dynamics', fontweight='bold')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # 2. Male Percentage Over Time
    ax2 = axes[1]
    ax2.plot(monthly_data['month'], monthly_data['male_percentage'], 
             linewidth=2.5, color='#4A90E2')
    ax2.axhline(y=50, color='red', linestyle='--', linewidth=2, 
                label='50% Threshold', alpha=0.7)
    ax2.fill_between(monthly_data['month'], 45, 55, alpha=0.2, color='green',
                     label='±5% from 50%')
    ax2.set_xlabel('Month', fontweight='bold')
    ax2.set_ylabel('Male Percentage (%)', fontweight='bold')
    ax2.set_title('Male Population Percentage', fontweight='bold')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim([40, 60])
    
    plt.tight_layout()
    plt.savefig('sex_ratio_analysis.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: sex_ratio_analysis.png")


def plot_individual_simulations(individual_sims, max_plots=5):
    """
    Plot individual simulation trajectories to show variability.
    
    Args:
        individual_sims (list): List of DataFrames containing individual simulation data
        max_plots (int): Maximum number of simulations to plot
    """
    if not individual_sims:
        print("⚠ No individual simulation files found. Skipping individual plots.")
        return
    
    fig, ax = plt.subplots(figsize=(14, 8))
    
    # Plot each simulation with transparency
    n_to_plot = min(len(individual_sims), max_plots)
    colors = plt.cm.viridis(np.linspace(0, 1, n_to_plot))
    
    for i, sim_df in enumerate(individual_sims[:n_to_plot]):
        ax.plot(sim_df['month'], sim_df['alive'], 
                linewidth=1.5, alpha=0.7, color=colors[i],
                label=f'Simulation {i+1}')
    
    ax.set_xlabel('Month', fontweight='bold', fontsize=12)
    ax.set_ylabel('Population', fontweight='bold', fontsize=12)
    ax.set_title('Individual Simulation Trajectories', fontweight='bold', fontsize=14)
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('individual_simulations.png', dpi=300, bbox_inches='tight')
    print(f"✓ Saved: individual_simulations.png (showing {n_to_plot} simulations)")


def print_summary_stats(summary_data):
    """
    Print summary statistics in a formatted table.
    
    Args:
        summary_data (DataFrame): Summary statistics data
    """
    print("\n" + "="*60)
    print(" " * 15 + "SIMULATION SUMMARY")
    print("="*60)
    
    # Create a dictionary for easy access
    stats = {row['metric']: row['value'] for _, row in summary_data.iterrows()}
    
    print(f"\n📊 Input Parameters:")
    print(f"   • Initial Population: {int(stats.get('initial_population', 0)):,}")
    print(f"   • Months Simulated: {int(stats.get('months_simulated', 0)):,}")
    print(f"   • Number of Simulations: {int(stats.get('number_of_simulations', 0)):,}")
    
    print(f"\n📈 Final Population Statistics:")
    print(f"   • Average Living Rabbits: {stats.get('avg_final_alive', 0):,.2f}")
    print(f"   • Average Total Deaths: {stats.get('avg_total_deaths', 0):,.2f}")
    
    print(f"\n🔝 Population Extremes:")
    print(f"   • Average Peak Population: {stats.get('avg_peak_population', 0):,.2f}")
    print(f"   • Average Minimum Population: {stats.get('avg_min_population', 0):,.2f}")
    
    print(f"\n💀 Extinction Analysis:")
    print(f"   • Extinctions: {int(stats.get('extinction_count', 0))} " +
          f"({stats.get('extinction_rate', 0):.1f}%)")
    
    print("\n" + "="*60 + "\n")


def main():
    """
    Main function to orchestrate the visualization process.
    """
    print("\n" + "="*60)
    print("   🐰 RABBIT SIMULATION DATA VISUALIZATION 🐰")
    print("="*60 + "\n")
    
    # Load data
    print("📁 Loading data files...")
    data = load_data()
    if data is None:
        sys.exit(1)
    
    monthly_avg, summary, individual_sims = data
    print(f"✓ Loaded monthly averages: {len(monthly_avg)} months")
    print(f"✓ Loaded summary statistics")
    print(f"✓ Loaded {len(individual_sims)} individual simulation(s)\n")
    
    # Print summary
    print_summary_stats(summary)
    
    # Generate visualizations
    print("📊 Generating visualizations...\n")
    
    try:
        plot_population_growth(monthly_avg, summary)
        plot_growth_rate(monthly_avg)
        plot_sex_ratio(monthly_avg)
        
        if individual_sims:
            plot_individual_simulations(individual_sims)
        
        print("\n" + "="*60)
        print("   ✅ ALL VISUALIZATIONS GENERATED SUCCESSFULLY!")
        print("="*60)
        print("\nGenerated files:")
        print("  • population_dynamics.png - Main population analysis")
        print("  • growth_rate_analysis.png - Growth rate trends")
        print("  • sex_ratio_analysis.png - Sex distribution analysis")
        if individual_sims:
            print("  • individual_simulations.png - Individual trajectories")
        print("\n")
        
    except Exception as e:
        print(f"\n❌ Error generating plots: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()